# Generated by Django 2.0.2 on 2023-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Cargo')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAtencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Atencion')),
                ('horaInicio', models.DateTimeField(auto_now_add=True, verbose_name='Hora Inicio')),
                ('horaFinal', models.DateTimeField(auto_now_add=True, verbose_name='Hora Final')),
                ('procedimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procedimiento Paciente')),
                ('diagnostico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnostico Paciente')),
                ('extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra Paciente')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rut Paciente')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Paciente')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono Paciente')),
                ('Sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo Paciente')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Paciente')),
                ('edad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edad Paciente')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Paciente')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rut Trabajador')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Trabajador')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono Trabajador')),
                ('Sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo Trabajador')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Trabajador')),
                ('edad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edad Trabajador')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Trabajador')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['nombre'],
            },
        ),
    ]
