# Generated by Django 2.0.2 on 2023-06-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudio.Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='trabajador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudio.Trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='state',
            field=models.CharField(choices=[('O', 'Odontologo'), ('S', 'Secretaria')], default='O', max_length=1),
        ),
    ]
