# Generated by Django 2.0.2 on 2023-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_auto_20230616_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechaAtencion',
            field=models.DateTimeField(verbose_name='Fecha Atencion'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaFinal',
            field=models.DateTimeField(verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaInicio',
            field=models.DateTimeField(verbose_name='Hora Inicio'),
        ),
    ]
