# Generated by Django 2.0.2 on 2023-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_auto_20230617_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaAtencion',
            field=models.DateField(verbose_name='Fecha Atencion'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaFinal',
            field=models.TimeField(verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaInicio',
            field=models.TimeField(verbose_name='Hora Inicio'),
        ),
    ]
