# Generated by Django 2.0.2 on 2023-06-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_auto_20230617_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='horaFinal',
        ),
    ]
